apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secure-api
  template:
    metadata:
      labels:
        app: secure-api
    spec:
      containers:
      - name: secure-api
        image: secure-api-k8s
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: secure-api-service
spec:
  type: NodePort
  selector:
    app: secure-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007
